### ISSUE TITLE
zoom factor for Popup Menu

### ISSUE THREAD

**Issue by Gerevett** [Pitmairen/selection-search#105]
Is it possible to set zoom factor for Popup Menu other than zoom factor for the page?

**Comment by Pitmairen** [comment]
You can increase the size of the popup by adding something like this to the custom css styling:

```css
.popup.mainmenu{
   transform: scale(1.5);
}
```
Append this to popup menu -> advanced settings -> customize -> text area.  This should increase the size of the popup. 

Depending on the scale number, you may have also have to tweak some other values for the popup to get positioned correctly.

**Comment by Gerevett** [comment]
Sorry, but this doesn't solve the problem. The idea was to set the scale of Popup Menu constant (like context menu), no matter how the page is scaled in browser. But zooming in/out the page (with Ctrl +/-) also changes the size of Popup Menu, even with this customization.

**Comment by Pitmairen** [comment]
Ok, I see what you mean. I don't know a reliable way to fix this. 

But something like this sort of works:
```css
@media (-webkit-min-device-pixel-ratio: 0.75) {.popup.mainmenu{transform: scale(calc(1 / 0.75));}}
@media (-webkit-min-device-pixel-ratio: 1) {.popup.mainmenu{transform: scale(calc(1 / 1));}}
@media (-webkit-min-device-pixel-ratio: 1.25) {.popup.mainmenu{transform: scale(calc(1 / 1.25));}}
@media (-webkit-min-device-pixel-ratio: 1.5) {.popup.mainmenu{transform: scale(calc(1 / 1.5));}}
@media (-webkit-min-device-pixel-ratio: 2) {.popup.mainmenu{transform: scale(calc(1 / 2));}}
```
But it's not perfect, and there is also some issues with the position of the menu.
