### ISSUE TITLE
Can a "circular popup" be customized as a css code?

### ISSUE THREAD

**Issue by asdf12340** [Pitmairen/selection-search#17]
Something like that for example..
![ribcx](https://cloud.githubusercontent.com/assets/4542113/10539570/b51ab22c-7400-11e5-87e8-6eddeaabafc2.jpg)

**Comment by Pitmairen** [comment]
Yes, it is possible. Below you can see a quick demo that I just made: 
![circular](https://cloud.githubusercontent.com/assets/357032/10542667/1f2a486c-741a-11e5-8209-c7ecd28c6ebf.png)

It is not very easy to make because the position of each search engine is hardcoded so every time 
a new search engine is added or removed the positions have to be updated. But it is done in pure CSS with no modifications to the code.

To make this usable, a script that can automatically generate the correct positions from the current search engines is probably needed.

**Comment by asdf12340** [comment]
I think this layout would be neat and more efficient, since every search icon would be equidistant from the mouse cursor.
Especially if two or three concentric circles could be customized as well..
Can you kindly provide me with the demo code you wrote?

**Comment by Pitmairen** [comment]
Here's the code:
It is probably not very useful to you though because it is hard coded for 9 search engines and also the center of the circle is not at the cursor position. It also breaks the preview on the options page.

But its an interesting design and something that I definitely want to add if I can find a good way to implement it.

```css
.popup{
 width: 70px;
 height: 70px;
 position: absolute;
 background: none;
 border-radius: 150px;
 border: 50px solid #333;
}
.popup > li:first-child{
 display: none;
}
.popup .engine-name{
 display: none;
}
.popup a {
 position: absolute;
 width: 20px;
 height: 25px;
 line-height: 25px;
}

.popup img{
 -webkit-filter: grayscale(95%);
}

.popup > li:nth-child(2) a{
 top: 20.5px;
 left: 89.5px;
}
.popup > li:nth-child(3) a{
 top: -21.28119462962505px;
 left: 74.29288880273357px;
}
.popup > li:nth-child(4) a{
 top: -43.512503945793526px;
 left: 35.78713154835047px;
}
.popup > li:nth-child(5) a{
 top: -35.79165124598852px;
 left: -7.999999999999986px;
}
.popup > li:nth-child(6) a{
 top: -1.7313093161684776px;
 left: -36.58002035108404px;
}
.popup > li:nth-child(7) a{
 top: 42.73130931616846px;
 left: -36.580020351084045px;
}
.popup > li:nth-child(8) a{
 top: 76.7916512459885px;
 left: -8.000000000000028px;
}
.popup > li:nth-child(9) a{
 top: 84.51250394579353px;
 left: 35.787131548350445px;
}
.popup > li:nth-child(10) a{
 top: 62.28119462962508px;
 left: 74.29288880273356px;
}
```

**Comment by asdf12340** [comment]
Neat, although i'm not quite sure why this's there for..
> .popup img{
 -webkit-filter: grayscale(95%);
} 

I tried to play around with the code a bit, and no matter what i do i can't make more than 5 icons appear in the  preview so i can adjust their position, however when i save and then try it on a web page, they appear normally.
![capture](https://cloud.githubusercontent.com/assets/4542113/10558343/11ecfd54-74cc-11e5-976e-b6fcada03eca.PNG)



So now, is it all about the script that could properly auto-align the search icons inside the circle?

**Comment by Pitmairen** [comment]
The grayscale  was added just to remove some color from the icons.

But I have a working version now that will auto create a circular menu. I just have to make an option to enable it in the option page and some fine tuning. I will upload a new version soon.

**Comment by asdf12340** [comment]
That's great news..
I hope this fine-tuning includes.
* An option to choose the position of the first Icon.
* An option to sort the icons Clockwise / Counter clockwise.
* The ability to use separators.
* An option to add concentric circles if possible.
* Make the mouse cursor be in the middle of popup.

Thank you and good luck.

**Comment by Pitmairen** [comment]
I have uploaded a new version with experimental circular menu support. 
It will open with the cursor in the middle, with the first icon at the top position. Sorting can be done by rearranging the order of the search engines. Separators will show, but only as dots because the positioning is not perfect at the moment.

**Comment by asdf12340** [comment]
Brilliant.
A couple of issue fro now ..
* It seems like, "Open all on click" doesn't work for sub-menus.
* Is there an easy way to add another circle? and distribute the search engines for each one?
because, as you can imagine, if one has a lot of icons, the circle's circumference gets very large, which takes more space and gets farther from the mouse.

**Comment by Pitmairen** [comment]
Open all on click still works, but the problem is that the sub menu opens above the icon. Even if the icon is visible because the sub menu background is transparent the sub menu is still above the icon so the click never reaches the icon below so the open all action is never executed. It still works though if you are very quick to click before the sub menu opens.  Also with the "Don't show menu" option on the sub menu it will work.

Multiple menus will probably require a rewrite of the internals of the extension. I'm not sure if i'm willing to do that. Currently the circular menu is implemented only by styling so everything else is the same as with the non-circular menu.

**Comment by asdf12340** [comment]
* Still doesn't work if i quickly tried to click it before the sub-menu opens, however it works if i checked "Don't show menu"

* Is the styling preview purposefully set on only showing 5 icons?

**Comment by Pitmairen** [comment]
1. You have to be very fast, it is probably hard to do on a touchpad if you are using a laptop.
2. That's a bug
3.  [Yes](https://github.com/Pitmairen/selection-search/blob/master/options/options.js#L180), it is intended as a quick preview of the styling, so only a few search engines is needed to see how it will look. With some of the styles, if someone has a lot of search engines the menu would become very long and fill a lot of the page if all the search engines was added.

**Comment by asdf12340** [comment]
I end up mistakenly pressing the wrong icon a lot, Can this get fixed by increasing the space between icons or the border radius to increase the effective area of pressing?
I noticed that as the number of icons increases, the space between them gets smaller.

**Comment by Pitmairen** [comment]
If you add the following to the css you can probably see what the problem is.
```css
.popup a:hover{
 background: green;
}
```
The problem is that the padding around the icons are to big. The green area is the area that will activate the search engine if you click. If the padding is reduced it will probably work better.

But the way the curcle is created right now was just something I put together very quick. I probably have to find a better way to make it more flexible and easier to customize.

**Comment by asdf12340** [comment]
Yeah, i've noticed it before, and i tried to customize the padding's height and width but it only changes the look, not the effective area of pressing.
Good luck..

**Comment by Nader3** [comment]
Any progress in improving the padding of the popup's hover, can it at all be improved by editing the styling css at all?

**Comment by Pitmairen** [comment]
I have made some improvements to the circular menu in the latest commits. You can test these changes by downloading the [the latest code](https://github.com/Pitmairen/selection-search/archive/4beb2c9ed7db9431803e63c06bfe865270c34684.zip) and load this as an unpacked extension on the extension page (chrome://extensions/). You can use the import/export feature to import your settings into the unpacked extension.

**Comment by Nader3** [comment]
Chrome couldn't unpack the extension showing "Could not load manifest." error.

**Comment by Pitmairen** [comment]
You have to unpack the zip manually and then select the folder which contains the manifest.json in the "load unpacked extension" dialog.

**Comment by Nader3** [comment]
Got it..
• Although it's at the cost of making the circle larger, the padding and the effective pressing area is much better now.
• The separators are going to be left as dots? or are you planning on making them lines?

**Comment by Pitmairen** [comment]
You can try to add the following css to make it a line, how well it works depends on if you have done any other tweaks to the css.
```css
.popup li.engine-separator{
 height: 30px;
 margin-top: 0;
 margin-left: 15px;
}
```

**Comment by Nader3** [comment]
yeah, it's great.
![untitled](https://cloud.githubusercontent.com/assets/4542113/10816914/00143b20-7e3f-11e5-968b-5e1e0c83d5a5.png)

**Comment by Nader3** [comment]
Can i disable the hover padding entirely? and make the effective area of clicking be just the size of the actual icon?
I can't do that from the css customization, so it must be hardcoded in the circular menu script.

**Comment by Pitmairen** [comment]
It's not the padding, it's the width.

You can try to tweak the width using the following
```css
.popup a{
  width: 0;
  height: 0;
  line-height: 0;
  margin-left: 5px;
  margin-top: 5px;
}
```
You probably have to tweak the margin and maybe some of the other values to align the icons properly.
