### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by GitAcc53** [Pitmairen/selection-search#172]
https://github.com/Pitmairen/selection-search/issues/143 This guy mentioned it but we still don't have dark theme. White texts with dark background would be great.

**Comment by sebastianzander** [comment]
Yes, please add a dark theme or ability to set foreground and background colors individually. Especially the light box shadow around the context menu looks very bad on top of dark websites.

**Comment by Pitmairen** [comment]
You can already do this if you know a bit of CSS.

You can test these examples by copy and pasting the below CSS into the text area under settings: 
`Toolbar Popup => Advanced Settings`.

You can use a color picker https://g.co/kgs/v6Vn5Dy to find the hex codes, if you want to adjust colors.  


Some examples:

![Image](https://github.com/user-attachments/assets/01c3e74a-55f1-466d-aead-ae77d0ced399)

```css
body{
  --bg-color-main: #333333;
  --bg-color-input: #4a4a4a;
  --bg-color-hover: #3a3a3a;
  --fg-color-main: #888888;
  --fg-color-hover: #999999;
}

body{
  background: var(--bg-color-main);
  color: var(--fg-color-main);
}
.search-input{
  background: var(--bg-color-input);
  color: var(--fg-color-main);
  border: none;
  outline: none;
}
.search-engines a{
  color: var(--fg-color-main);
}
.search-engines a:hover{
  background: var(--bg-color-hover);
  color: var(--fg-color-hover);
}
.suggestions{
  background: var(--bg-color-input);
}
.suggestions a{
  color: var(--fg-color-main);
}
.suggestions a:hover{
  color: var(--fg-color-hover);
}
```

The same but with gray icons:

![Image](https://github.com/user-attachments/assets/7d3681a5-d03d-4ed5-971a-e7569c9a8463)

```css
body{
  --bg-color-main: #333333;
  --bg-color-input: #4a4a4a;
  --bg-color-hover: #3a3a3a;
  --fg-color-main: #888888;
  --fg-color-hover: #999999;
}

body{
  background: var(--bg-color-main);
  color: var(--fg-color-main);
}
.search-input{
  background: var(--bg-color-input);
  color: var(--fg-color-main);
  border: none;
  outline: none;
}
.search-engines a{
  color: var(--fg-color-main);
}
.search-engines a:hover{
  background: var(--bg-color-hover);
  color: var(--fg-color-hover);
}
.suggestions{
  background: var(--bg-color-input);
}
.suggestions a{
  color: var(--fg-color-main);
}
.suggestions a:hover{
  color: var(--fg-color-hover);
}
.search-engines img{
 filter: grayscale(1);
}
```

Change the size a bit and also add separators:

![Image](https://github.com/user-attachments/assets/b153063a-687c-4304-93f8-879f59268ad1)

```css
body{
  --bg-color-main: #333333;
  --bg-color-input: #4a4a4a;
  --bg-color-hover: #3a3a3a;
  --fg-color-main: #888888;
  --fg-color-hover: #999999;
  --separator-color: #4a4a4a;
}

body{
  background: var(--bg-color-main);
  color: var(--fg-color-main);
}
.search-input{
  background: var(--bg-color-input);
  color: var(--fg-color-main);
  border: none;
  outline: none;
}
.search-engines a{
  color: var(--fg-color-main);
}
.search-engines a:hover{
  background: var(--bg-color-hover);
  color: var(--fg-color-hover);
}
.suggestions{
  background: var(--bg-color-input);
}
.suggestions a{
  color: var(--fg-color-main);
}
.suggestions a:hover{
  color: var(--fg-color-hover);
}
.container{
  width: 500px;
}
.search-engines li{
 flex: 0 20%;
 width: 1em;
}
.search-engines img{
 width: 12px;
 height: 12px;
 border-radius: 50%;
}
.search-engines .separator::after{
    content: "";
    background: var(--separator-color);
    height: 1px;
    flex: 1;
}
.search-engines .separator{
    display: flex;
    align-items: center;
    flex: 1 100%;
    margin: 0.2em 0;
}
```

**Comment by sebastianzander** [comment]
I wasn't even expecting this much configurability. And yes, I know one or two things about CSS and can help myself now. Thank you, @Pitmairen.

**Comment by GitAcc53** [comment]
Any way to make folders yellow instead of transparent?

**Comment by Pitmairen** [comment]
For the default icon, it is possible with a css trick.

Try to add this to your css, there may be other ways to do this as well.
```css
img.engine-img[src*="/img/folder.svg"] {
    filter: drop-shadow(100vw 0 0 yellow);
    transform: translateX(-100vw);
}
```

Alternatively, you can find an icon somewhere on the internet, that looks the way you want, and then copy the url of the icon into the "icon url" of the sub menu in the settings. Then you can have any icon you want.
