### ISSUE TITLE
[How to CSS] How to add a search box in a 'icons only' popup?

### ISSUE THREAD

**Issue by Droyk** [Pitmairen/selection-search#70]
![image](https://user-images.githubusercontent.com/15848350/62955321-77308980-be0e-11e9-916b-41619e4b87d5.png)

I want the same search widget/box/bar on a icons only popup. so please help me to make it possible!!

**Comment by Pitmairen** [comment]
Try to append the following to the bottom of the css for the icon only style:

Icons on a single line with text input above:
```css
.popup.mainmenu > li:first-child{
  display: block;
  padding: 0.3em;
}
.popup input{
  width: 100%;
}
```


If you have many search engines, the icons can be broken into multiple lines using this:
```css
.popup.mainmenu > li:first-child{
  display: block;
  padding: 0.3em;
  float: none;
}
.popup input{
  width: 100%;
}
.popup {
   width: 150px;
}
.popup li{
   float: left;
}
```

**Comment by Droyk** [comment]
@Pitmairen I only want the search widget, I don't want to vertically align my icons with text. I just want the search widget that can be used with icons only pop-up menu!!

Something like this!! 
![image](https://user-images.githubusercontent.com/15848350/63042498-c0a0d780-bee7-11e9-8693-8c4a21164af7.png)

**Comment by Pitmairen** [comment]
This is how it looks for me with the first css code above:


![Screenshot_20190814_211935](https://user-images.githubusercontent.com/357032/63049561-42d5cf80-bed9-11e9-9cf9-91420834b97e.png)


This is how the second css code look with more search engines:
![Screenshot_20190814_212151](https://user-images.githubusercontent.com/357032/63049688-8a5c5b80-bed9-11e9-9184-895f124ef349.png)


In these examples I have appended the above css to the bottom of the textarea under popup -> advanced settings -> styling -> icon only -> customize.

**Comment by Droyk** [comment]
Hey, apologies it seems like I was pasting it wrong 😓

For the 2nd one
> This is how the second css code look with more search engines:
> ![Screenshot_20190814_212151](https://user-images.githubusercontent.com/357032/63049688-8a5c5b80-bed9-11e9-9184-895f124ef349.png)
> 
> In these examples I have appended the above css to the bottom of the textarea under popup -> advanced settings -> styling -> icon only -> customize.

for me, it only behaves like that around the edge of the window it changes its shape from a straight line to the column around the edge of the window and in the centre of the page, the popup menu becomes a straight line again.

**Comment by Droyk** [comment]
https://gfycat.com/plaintivepinkamericanbittern

**Comment by Pitmairen** [comment]
You added it in the wrong position. The order of the css statements are important. The last/bottom statements will override the above. 

In the code you pasted you added this: 
```
.popup {
  width: 150px;
}
```
but below that is the following that will change the with back to auto:
```
.popup {
 width: auto;
 padding: 0.1em;
 white-space:nowrap;
}
```

Try this:
```css
.popup .engine-name, .popup.mainmenu > li:first-child{
 display: none;
}
.popup a, .popup li{
 display: inline-block; padding: 0.2em;
}
.popup img{
 margin: 0; padding: 0;
}
.popup {
 width: auto;
 padding: 0.1em;
 white-space:nowrap;
}
.popup .engine-separator{
 width: 1px; height: 20px; margin: 0 3px 3px 3px; padding: 0; vertical-align: middle;
}
/*CONFIG_START{"submenu_position":"topright","submenu_corner":"bottomleft"}CONFIG_END*/
.popup.mainmenu > li:first-child{
  display: block;
  padding: 0.3em;
  float: none;
}
.popup input{
  width: 100%;
}
.popup {
   width: 150px;
}
.popup li{
   float: left;
}
```

It is possible to clean this up a little bit, but I didn't bother to do that, I just added the code to the bottom to make sure it takes precedence.

**Comment by Droyk** [comment]
![image](https://user-images.githubusercontent.com/15848350/63053661-f2be3380-beff-11e9-9fd3-4c5847557a6d.png)
whitespace because of a separator 😔 
instead of a vertical separator possible to make a horizontal separator via CSS to match the column style popup or better to automatically change it to vertical one on a single line popup menu & change it back to horizontal one on column popup.

**Comment by Pitmairen** [comment]
Try to add the following css:
```css
.popup .engine-separator {
  width: 100%;
  height: 1px;
}
```
