### ISSUE TITLE
How to fit the position of the Popup Menu?

### ISSUE THREAD

**Issue by radioterror** [Pitmairen/selection-search#85]
Im becoming mad trying to change this:
![I dont like this](https://user-images.githubusercontent.com/29166683/79051012-073d0200-7c2e-11ea-9c73-bca77deca14e.png)
to this:
![I want this](https://user-images.githubusercontent.com/29166683/79051015-1328c400-7c2e-11ea-801d-8400d3e38e73.png)

**Comment by Pitmairen** [comment]
Try to add this to the popup -> advanced -> customize -> textarea:

```css
.popup.mainmenu{
    transform: translate(-50%, 11px);
}
```
You can tweak the values to position it to your liking.
